// Code generated by go generate; DO NOT EDIT.
// 2019-01-27 23:08:03.577051096 -0500 EST m=+0.001488989
package mpv

import (
	"fmt"
)

// property getters
func (c *Client) GetProperty(name string) (prop interface{}, err error) {
	ch, err := c.Execute("get_property", name)
	reply, err := ReplyOrTimeout(ch, WaitForReply)
	if err != nil {
		err = fmt.Errorf("mpv.GetProperty: '%s': %s", name, err)
		return
	}
	if reply.Error != "success" {
		err = fmt.Errorf("mpv.GetProperty: '%s': %s", name, reply.Error)
		return
	}
	prop = reply.Data

	return
}

// OsdLevel gets 'osd-level' property
func (c *Client) OsdLevel() (prop interface{}, err error) {
	return c.GetProperty("osd-level")
}

// OsdScale gets 'osd-scale' property
func (c *Client) OsdScale() (prop interface{}, err error) {
	return c.GetProperty("osd-scale")
}

// Loop gets 'loop' property
func (c *Client) Loop() (prop interface{}, err error) {
	return c.GetProperty("loop")
}

// LoopFile gets 'loop-file' property
func (c *Client) LoopFile() (prop interface{}, err error) {
	return c.GetProperty("loop-file")
}

// Speed gets 'speed' property
func (c *Client) Speed() (prop interface{}, err error) {
	return c.GetProperty("speed")
}

// AudioSpeedCorrection gets 'audio-speed-correction' property
func (c *Client) AudioSpeedCorrection() (prop interface{}, err error) {
	return c.GetProperty("audio-speed-correction")
}

// VideoSpeedCorrection gets 'video-speed-correction' property
func (c *Client) VideoSpeedCorrection() (prop interface{}, err error) {
	return c.GetProperty("video-speed-correction")
}

// DisplaySyncActive gets 'display-sync-active' property
func (c *Client) DisplaySyncActive() (prop interface{}, err error) {
	return c.GetProperty("display-sync-active")
}

// Filename gets 'filename' property
func (c *Client) Filename() (prop interface{}, err error) {
	return c.GetProperty("filename")
}

// StreamOpenFilename gets 'stream-open-filename' property
func (c *Client) StreamOpenFilename() (prop interface{}, err error) {
	return c.GetProperty("stream-open-filename")
}

// FileSize gets 'file-size' property
func (c *Client) FileSize() (prop interface{}, err error) {
	return c.GetProperty("file-size")
}

// Path gets 'path' property
func (c *Client) Path() (prop interface{}, err error) {
	return c.GetProperty("path")
}

// MediaTitle gets 'media-title' property
func (c *Client) MediaTitle() (prop interface{}, err error) {
	return c.GetProperty("media-title")
}

// StreamPath gets 'stream-path' property
func (c *Client) StreamPath() (prop interface{}, err error) {
	return c.GetProperty("stream-path")
}

// StreamCapture gets 'stream-capture' property
func (c *Client) StreamCapture() (prop interface{}, err error) {
	return c.GetProperty("stream-capture")
}

// Demuxer gets 'demuxer' property
func (c *Client) Demuxer() (prop interface{}, err error) {
	return c.GetProperty("demuxer")
}

// FileFormat gets 'file-format' property
func (c *Client) FileFormat() (prop interface{}, err error) {
	return c.GetProperty("file-format")
}

// StreamPos gets 'stream-pos' property
func (c *Client) StreamPos() (prop interface{}, err error) {
	return c.GetProperty("stream-pos")
}

// StreamEnd gets 'stream-end' property
func (c *Client) StreamEnd() (prop interface{}, err error) {
	return c.GetProperty("stream-end")
}

// Duration gets 'duration' property
func (c *Client) Duration() (prop interface{}, err error) {
	return c.GetProperty("duration")
}

// Length gets 'length' property
func (c *Client) Length() (prop interface{}, err error) {
	return c.GetProperty("length")
}

// Avsync gets 'avsync' property
func (c *Client) Avsync() (prop interface{}, err error) {
	return c.GetProperty("avsync")
}

// TotalAvsyncChange gets 'total-avsync-change' property
func (c *Client) TotalAvsyncChange() (prop interface{}, err error) {
	return c.GetProperty("total-avsync-change")
}

// DropFrameCount gets 'drop-frame-count' property
func (c *Client) DropFrameCount() (prop interface{}, err error) {
	return c.GetProperty("drop-frame-count")
}

// MistimedFrameCount gets 'mistimed-frame-count' property
func (c *Client) MistimedFrameCount() (prop interface{}, err error) {
	return c.GetProperty("mistimed-frame-count")
}

// VsyncRatio gets 'vsync-ratio' property
func (c *Client) VsyncRatio() (prop interface{}, err error) {
	return c.GetProperty("vsync-ratio")
}

// VoDropFrameCount gets 'vo-drop-frame-count' property
func (c *Client) VoDropFrameCount() (prop interface{}, err error) {
	return c.GetProperty("vo-drop-frame-count")
}

// VoDelayedFrameCount gets 'vo-delayed-frame-count' property
func (c *Client) VoDelayedFrameCount() (prop interface{}, err error) {
	return c.GetProperty("vo-delayed-frame-count")
}

// PercentPos gets 'percent-pos' property
func (c *Client) PercentPos() (prop interface{}, err error) {
	return c.GetProperty("percent-pos")
}

// TimeStart gets 'time-start' property
func (c *Client) TimeStart() (prop interface{}, err error) {
	return c.GetProperty("time-start")
}

// TimePos gets 'time-pos' property
func (c *Client) TimePos() (prop interface{}, err error) {
	return c.GetProperty("time-pos")
}

// TimeRemaining gets 'time-remaining' property
func (c *Client) TimeRemaining() (prop interface{}, err error) {
	return c.GetProperty("time-remaining")
}

// PlaytimeRemaining gets 'playtime-remaining' property
func (c *Client) PlaytimeRemaining() (prop interface{}, err error) {
	return c.GetProperty("playtime-remaining")
}

// PlaybackTime gets 'playback-time' property
func (c *Client) PlaybackTime() (prop interface{}, err error) {
	return c.GetProperty("playback-time")
}

// DiscTitle gets 'disc-title' property
func (c *Client) DiscTitle() (prop interface{}, err error) {
	return c.GetProperty("disc-title")
}

// Chapter gets 'chapter' property
func (c *Client) Chapter() (prop interface{}, err error) {
	return c.GetProperty("chapter")
}

// Edition gets 'edition' property
func (c *Client) Edition() (prop interface{}, err error) {
	return c.GetProperty("edition")
}

// DiscTitles gets 'disc-titles' property
func (c *Client) DiscTitles() (prop interface{}, err error) {
	return c.GetProperty("disc-titles")
}

// Chapters gets 'chapters' property
func (c *Client) Chapters() (prop interface{}, err error) {
	return c.GetProperty("chapters")
}

// Editions gets 'editions' property
func (c *Client) Editions() (prop interface{}, err error) {
	return c.GetProperty("editions")
}

// Angle gets 'angle' property
func (c *Client) Angle() (prop interface{}, err error) {
	return c.GetProperty("angle")
}

// Metadata gets 'metadata' property
func (c *Client) Metadata() (prop interface{}, err error) {
	return c.GetProperty("metadata")
}

// FilteredMetadata gets 'filtered-metadata' property
func (c *Client) FilteredMetadata() (prop interface{}, err error) {
	return c.GetProperty("filtered-metadata")
}

// ChapterMetadata gets 'chapter-metadata' property
func (c *Client) ChapterMetadata() (prop interface{}, err error) {
	return c.GetProperty("chapter-metadata")
}

// VfMetadata gets 'vf-metadata' property
func (c *Client) VfMetadata() (prop interface{}, err error) {
	return c.GetProperty("vf-metadata")
}

// AfMetadata gets 'af-metadata' property
func (c *Client) AfMetadata() (prop interface{}, err error) {
	return c.GetProperty("af-metadata")
}

// Pause gets 'pause' property
func (c *Client) Pause() (prop interface{}, err error) {
	return c.GetProperty("pause")
}

// CoreIdle gets 'core-idle' property
func (c *Client) CoreIdle() (prop interface{}, err error) {
	return c.GetProperty("core-idle")
}

// EofReached gets 'eof-reached' property
func (c *Client) EofReached() (prop interface{}, err error) {
	return c.GetProperty("eof-reached")
}

// Seeking gets 'seeking' property
func (c *Client) Seeking() (prop interface{}, err error) {
	return c.GetProperty("seeking")
}

// PlaybackAbort gets 'playback-abort' property
func (c *Client) PlaybackAbort() (prop interface{}, err error) {
	return c.GetProperty("playback-abort")
}

// Cache gets 'cache' property
func (c *Client) Cache() (prop interface{}, err error) {
	return c.GetProperty("cache")
}

// CacheFree gets 'cache-free' property
func (c *Client) CacheFree() (prop interface{}, err error) {
	return c.GetProperty("cache-free")
}

// CacheUsed gets 'cache-used' property
func (c *Client) CacheUsed() (prop interface{}, err error) {
	return c.GetProperty("cache-used")
}

// CacheSize gets 'cache-size' property
func (c *Client) CacheSize() (prop interface{}, err error) {
	return c.GetProperty("cache-size")
}

// CacheIdle gets 'cache-idle' property
func (c *Client) CacheIdle() (prop interface{}, err error) {
	return c.GetProperty("cache-idle")
}

// DemuxerCacheDuration gets 'demuxer-cache-duration' property
func (c *Client) DemuxerCacheDuration() (prop interface{}, err error) {
	return c.GetProperty("demuxer-cache-duration")
}

// DemuxerCacheTime gets 'demuxer-cache-time' property
func (c *Client) DemuxerCacheTime() (prop interface{}, err error) {
	return c.GetProperty("demuxer-cache-time")
}

// DemuxerCacheIdle gets 'demuxer-cache-idle' property
func (c *Client) DemuxerCacheIdle() (prop interface{}, err error) {
	return c.GetProperty("demuxer-cache-idle")
}

// CacheBufferingState gets 'cache-buffering-state' property
func (c *Client) CacheBufferingState() (prop interface{}, err error) {
	return c.GetProperty("cache-buffering-state")
}

// PausedForCache gets 'paused-for-cache' property
func (c *Client) PausedForCache() (prop interface{}, err error) {
	return c.GetProperty("paused-for-cache")
}

// HrSeek gets 'hr-seek' property
func (c *Client) HrSeek() (prop interface{}, err error) {
	return c.GetProperty("hr-seek")
}

// Clock gets 'clock' property
func (c *Client) Clock() (prop interface{}, err error) {
	return c.GetProperty("clock")
}

// Seekable gets 'seekable' property
func (c *Client) Seekable() (prop interface{}, err error) {
	return c.GetProperty("seekable")
}

// PartiallySeekable gets 'partially-seekable' property
func (c *Client) PartiallySeekable() (prop interface{}, err error) {
	return c.GetProperty("partially-seekable")
}

// Idle gets 'idle' property
func (c *Client) Idle() (prop interface{}, err error) {
	return c.GetProperty("idle")
}

// ChapterList gets 'chapter-list' property
func (c *Client) ChapterList() (prop interface{}, err error) {
	return c.GetProperty("chapter-list")
}

// TrackList gets 'track-list' property
func (c *Client) TrackList() (prop interface{}, err error) {
	return c.GetProperty("track-list")
}

// EditionList gets 'edition-list' property
func (c *Client) EditionList() (prop interface{}, err error) {
	return c.GetProperty("edition-list")
}

// DiscTitleList gets 'disc-title-list' property
func (c *Client) DiscTitleList() (prop interface{}, err error) {
	return c.GetProperty("disc-title-list")
}

// Playlist gets 'playlist' property
func (c *Client) Playlist() (prop interface{}, err error) {
	return c.GetProperty("playlist")
}

// PlaylistPos gets 'playlist-pos' property
func (c *Client) PlaylistPos() (prop interface{}, err error) {
	return c.GetProperty("playlist-pos")
}

// PlaylistCount gets 'playlist-count' property
func (c *Client) PlaylistCount() (prop interface{}, err error) {
	return c.GetProperty("playlist-count")
}

// Volume gets 'volume' property
func (c *Client) Volume() (prop interface{}, err error) {
	return c.GetProperty("volume")
}

// Mute gets 'mute' property
func (c *Client) Mute() (prop interface{}, err error) {
	return c.GetProperty("mute")
}

// AudioDelay gets 'audio-delay' property
func (c *Client) AudioDelay() (prop interface{}, err error) {
	return c.GetProperty("audio-delay")
}

// AudioCodecName gets 'audio-codec-name' property
func (c *Client) AudioCodecName() (prop interface{}, err error) {
	return c.GetProperty("audio-codec-name")
}

// AudioCodec gets 'audio-codec' property
func (c *Client) AudioCodec() (prop interface{}, err error) {
	return c.GetProperty("audio-codec")
}

// AudioParams gets 'audio-params' property
func (c *Client) AudioParams() (prop interface{}, err error) {
	return c.GetProperty("audio-params")
}

// AudioOutParams gets 'audio-out-params' property
func (c *Client) AudioOutParams() (prop interface{}, err error) {
	return c.GetProperty("audio-out-params")
}

// AudioSamplerate gets 'audio-samplerate' property
func (c *Client) AudioSamplerate() (prop interface{}, err error) {
	return c.GetProperty("audio-samplerate")
}

// AudioChannels gets 'audio-channels' property
func (c *Client) AudioChannels() (prop interface{}, err error) {
	return c.GetProperty("audio-channels")
}

// Aid gets 'aid' property
func (c *Client) Aid() (prop interface{}, err error) {
	return c.GetProperty("aid")
}

// Balance gets 'balance' property
func (c *Client) Balance() (prop interface{}, err error) {
	return c.GetProperty("balance")
}

// VolumeRestoreData gets 'volume-restore-data' property
func (c *Client) VolumeRestoreData() (prop interface{}, err error) {
	return c.GetProperty("volume-restore-data")
}

// AudioDevice gets 'audio-device' property
func (c *Client) AudioDevice() (prop interface{}, err error) {
	return c.GetProperty("audio-device")
}

// AudioDeviceList gets 'audio-device-list' property
func (c *Client) AudioDeviceList() (prop interface{}, err error) {
	return c.GetProperty("audio-device-list")
}

// CurrentAo gets 'current-ao' property
func (c *Client) CurrentAo() (prop interface{}, err error) {
	return c.GetProperty("current-ao")
}

// AudioOutDetectedDevice gets 'audio-out-detected-device' property
func (c *Client) AudioOutDetectedDevice() (prop interface{}, err error) {
	return c.GetProperty("audio-out-detected-device")
}

// Fullscreen gets 'fullscreen' property
func (c *Client) Fullscreen() (prop interface{}, err error) {
	return c.GetProperty("fullscreen")
}

// Deinterlace gets 'deinterlace' property
func (c *Client) Deinterlace() (prop interface{}, err error) {
	return c.GetProperty("deinterlace")
}

// FieldDominance gets 'field-dominance' property
func (c *Client) FieldDominance() (prop interface{}, err error) {
	return c.GetProperty("field-dominance")
}

// Ontop gets 'ontop' property
func (c *Client) Ontop() (prop interface{}, err error) {
	return c.GetProperty("ontop")
}

// Border gets 'border' property
func (c *Client) Border() (prop interface{}, err error) {
	return c.GetProperty("border")
}

// OnAllWorkspaces gets 'on-all-workspaces' property
func (c *Client) OnAllWorkspaces() (prop interface{}, err error) {
	return c.GetProperty("on-all-workspaces")
}

// Framedrop gets 'framedrop' property
func (c *Client) Framedrop() (prop interface{}, err error) {
	return c.GetProperty("framedrop")
}

// Gamma gets 'gamma' property
func (c *Client) Gamma() (prop interface{}, err error) {
	return c.GetProperty("gamma")
}

// Brightness gets 'brightness' property
func (c *Client) Brightness() (prop interface{}, err error) {
	return c.GetProperty("brightness")
}

// Contrast gets 'contrast' property
func (c *Client) Contrast() (prop interface{}, err error) {
	return c.GetProperty("contrast")
}

// Saturation gets 'saturation' property
func (c *Client) Saturation() (prop interface{}, err error) {
	return c.GetProperty("saturation")
}

// Hue gets 'hue' property
func (c *Client) Hue() (prop interface{}, err error) {
	return c.GetProperty("hue")
}

// VideoOutputLevels gets 'video-output-levels' property
func (c *Client) VideoOutputLevels() (prop interface{}, err error) {
	return c.GetProperty("video-output-levels")
}

// Panscan gets 'panscan' property
func (c *Client) Panscan() (prop interface{}, err error) {
	return c.GetProperty("panscan")
}

// VideoZoom gets 'video-zoom' property
func (c *Client) VideoZoom() (prop interface{}, err error) {
	return c.GetProperty("video-zoom")
}

// VideoAlignX gets 'video-align-x' property
func (c *Client) VideoAlignX() (prop interface{}, err error) {
	return c.GetProperty("video-align-x")
}

// VideoAlignY gets 'video-align-y' property
func (c *Client) VideoAlignY() (prop interface{}, err error) {
	return c.GetProperty("video-align-y")
}

// VideoPanX gets 'video-pan-x' property
func (c *Client) VideoPanX() (prop interface{}, err error) {
	return c.GetProperty("video-pan-x")
}

// VideoPanY gets 'video-pan-y' property
func (c *Client) VideoPanY() (prop interface{}, err error) {
	return c.GetProperty("video-pan-y")
}

// VideoUnscaled gets 'video-unscaled' property
func (c *Client) VideoUnscaled() (prop interface{}, err error) {
	return c.GetProperty("video-unscaled")
}

// VideoOutParams gets 'video-out-params' property
func (c *Client) VideoOutParams() (prop interface{}, err error) {
	return c.GetProperty("video-out-params")
}

// VideoParams gets 'video-params' property
func (c *Client) VideoParams() (prop interface{}, err error) {
	return c.GetProperty("video-params")
}

// VideoFormat gets 'video-format' property
func (c *Client) VideoFormat() (prop interface{}, err error) {
	return c.GetProperty("video-format")
}

// VideoFrameInfo gets 'video-frame-info' property
func (c *Client) VideoFrameInfo() (prop interface{}, err error) {
	return c.GetProperty("video-frame-info")
}

// VideoCodec gets 'video-codec' property
func (c *Client) VideoCodec() (prop interface{}, err error) {
	return c.GetProperty("video-codec")
}

// Dwidth gets 'dwidth' property
func (c *Client) Dwidth() (prop interface{}, err error) {
	return c.GetProperty("dwidth")
}

// Dheight gets 'dheight' property
func (c *Client) Dheight() (prop interface{}, err error) {
	return c.GetProperty("dheight")
}

// Width gets 'width' property
func (c *Client) Width() (prop interface{}, err error) {
	return c.GetProperty("width")
}

// Height gets 'height' property
func (c *Client) Height() (prop interface{}, err error) {
	return c.GetProperty("height")
}

// WindowScale gets 'window-scale' property
func (c *Client) WindowScale() (prop interface{}, err error) {
	return c.GetProperty("window-scale")
}

// VoConfigured gets 'vo-configured' property
func (c *Client) VoConfigured() (prop interface{}, err error) {
	return c.GetProperty("vo-configured")
}

// CurrentVo gets 'current-vo' property
func (c *Client) CurrentVo() (prop interface{}, err error) {
	return c.GetProperty("current-vo")
}

// Fps gets 'fps' property
func (c *Client) Fps() (prop interface{}, err error) {
	return c.GetProperty("fps")
}

// EstimatedVfFps gets 'estimated-vf-fps' property
func (c *Client) EstimatedVfFps() (prop interface{}, err error) {
	return c.GetProperty("estimated-vf-fps")
}

// VideoAspect gets 'video-aspect' property
func (c *Client) VideoAspect() (prop interface{}, err error) {
	return c.GetProperty("video-aspect")
}

// Vid gets 'vid' property
func (c *Client) Vid() (prop interface{}, err error) {
	return c.GetProperty("vid")
}

// Program gets 'program' property
func (c *Client) Program() (prop interface{}, err error) {
	return c.GetProperty("program")
}

// Hwdec gets 'hwdec' property
func (c *Client) Hwdec() (prop interface{}, err error) {
	return c.GetProperty("hwdec")
}

// HwdecActive gets 'hwdec-active' property
func (c *Client) HwdecActive() (prop interface{}, err error) {
	return c.GetProperty("hwdec-active")
}

// HwdecDetected gets 'hwdec-detected' property
func (c *Client) HwdecDetected() (prop interface{}, err error) {
	return c.GetProperty("hwdec-detected")
}

// EstimatedFrameCount gets 'estimated-frame-count' property
func (c *Client) EstimatedFrameCount() (prop interface{}, err error) {
	return c.GetProperty("estimated-frame-count")
}

// EstimatedFrameNumber gets 'estimated-frame-number' property
func (c *Client) EstimatedFrameNumber() (prop interface{}, err error) {
	return c.GetProperty("estimated-frame-number")
}

// OsdWidth gets 'osd-width' property
func (c *Client) OsdWidth() (prop interface{}, err error) {
	return c.GetProperty("osd-width")
}

// OsdHeight gets 'osd-height' property
func (c *Client) OsdHeight() (prop interface{}, err error) {
	return c.GetProperty("osd-height")
}

// OsdPar gets 'osd-par' property
func (c *Client) OsdPar() (prop interface{}, err error) {
	return c.GetProperty("osd-par")
}

// OsdSymCc gets 'osd-sym-cc' property
func (c *Client) OsdSymCc() (prop interface{}, err error) {
	return c.GetProperty("osd-sym-cc")
}

// OsdAssCc gets 'osd-ass-cc' property
func (c *Client) OsdAssCc() (prop interface{}, err error) {
	return c.GetProperty("osd-ass-cc")
}

// Sid gets 'sid' property
func (c *Client) Sid() (prop interface{}, err error) {
	return c.GetProperty("sid")
}

// SecondarySid gets 'secondary-sid' property
func (c *Client) SecondarySid() (prop interface{}, err error) {
	return c.GetProperty("secondary-sid")
}

// SubDelay gets 'sub-delay' property
func (c *Client) SubDelay() (prop interface{}, err error) {
	return c.GetProperty("sub-delay")
}

// SubPos gets 'sub-pos' property
func (c *Client) SubPos() (prop interface{}, err error) {
	return c.GetProperty("sub-pos")
}

// SubVisibility gets 'sub-visibility' property
func (c *Client) SubVisibility() (prop interface{}, err error) {
	return c.GetProperty("sub-visibility")
}

// SubForcedOnly gets 'sub-forced-only' property
func (c *Client) SubForcedOnly() (prop interface{}, err error) {
	return c.GetProperty("sub-forced-only")
}

// SubScale gets 'sub-scale' property
func (c *Client) SubScale() (prop interface{}, err error) {
	return c.GetProperty("sub-scale")
}

// SubUseMargins gets 'sub-use-margins' property
func (c *Client) SubUseMargins() (prop interface{}, err error) {
	return c.GetProperty("sub-use-margins")
}

// AssForceMargins gets 'ass-force-margins' property
func (c *Client) AssForceMargins() (prop interface{}, err error) {
	return c.GetProperty("ass-force-margins")
}

// AssVsfilterAspectCompat gets 'ass-vsfilter-aspect-compat' property
func (c *Client) AssVsfilterAspectCompat() (prop interface{}, err error) {
	return c.GetProperty("ass-vsfilter-aspect-compat")
}

// AssStyleOverride gets 'ass-style-override' property
func (c *Client) AssStyleOverride() (prop interface{}, err error) {
	return c.GetProperty("ass-style-override")
}

// VideoRotate gets 'video-rotate' property
func (c *Client) VideoRotate() (prop interface{}, err error) {
	return c.GetProperty("video-rotate")
}

// AbLoopA gets 'ab-loop-a' property
func (c *Client) AbLoopA() (prop interface{}, err error) {
	return c.GetProperty("ab-loop-a")
}

// AbLoopB gets 'ab-loop-b' property
func (c *Client) AbLoopB() (prop interface{}, err error) {
	return c.GetProperty("ab-loop-b")
}

// PacketVideoBitrate gets 'packet-video-bitrate' property
func (c *Client) PacketVideoBitrate() (prop interface{}, err error) {
	return c.GetProperty("packet-video-bitrate")
}

// PacketAudioBitrate gets 'packet-audio-bitrate' property
func (c *Client) PacketAudioBitrate() (prop interface{}, err error) {
	return c.GetProperty("packet-audio-bitrate")
}

// PacketSubBitrate gets 'packet-sub-bitrate' property
func (c *Client) PacketSubBitrate() (prop interface{}, err error) {
	return c.GetProperty("packet-sub-bitrate")
}

// VideoBitrate gets 'video-bitrate' property
func (c *Client) VideoBitrate() (prop interface{}, err error) {
	return c.GetProperty("video-bitrate")
}

// AudioBitrate gets 'audio-bitrate' property
func (c *Client) AudioBitrate() (prop interface{}, err error) {
	return c.GetProperty("audio-bitrate")
}

// SubBitrate gets 'sub-bitrate' property
func (c *Client) SubBitrate() (prop interface{}, err error) {
	return c.GetProperty("sub-bitrate")
}

// TvBrightness gets 'tv-brightness' property
func (c *Client) TvBrightness() (prop interface{}, err error) {
	return c.GetProperty("tv-brightness")
}

// TvContrast gets 'tv-contrast' property
func (c *Client) TvContrast() (prop interface{}, err error) {
	return c.GetProperty("tv-contrast")
}

// TvSaturation gets 'tv-saturation' property
func (c *Client) TvSaturation() (prop interface{}, err error) {
	return c.GetProperty("tv-saturation")
}

// TvHue gets 'tv-hue' property
func (c *Client) TvHue() (prop interface{}, err error) {
	return c.GetProperty("tv-hue")
}

// TvFreq gets 'tv-freq' property
func (c *Client) TvFreq() (prop interface{}, err error) {
	return c.GetProperty("tv-freq")
}

// TvNorm gets 'tv-norm' property
func (c *Client) TvNorm() (prop interface{}, err error) {
	return c.GetProperty("tv-norm")
}

// TvScan gets 'tv-scan' property
func (c *Client) TvScan() (prop interface{}, err error) {
	return c.GetProperty("tv-scan")
}

// TvChannel gets 'tv-channel' property
func (c *Client) TvChannel() (prop interface{}, err error) {
	return c.GetProperty("tv-channel")
}

// DvbChannel gets 'dvb-channel' property
func (c *Client) DvbChannel() (prop interface{}, err error) {
	return c.GetProperty("dvb-channel")
}

// CursorAutohide gets 'cursor-autohide' property
func (c *Client) CursorAutohide() (prop interface{}, err error) {
	return c.GetProperty("cursor-autohide")
}

// FfVid gets 'ff-vid' property
func (c *Client) FfVid() (prop interface{}, err error) {
	return c.GetProperty("ff-vid")
}

// FfAid gets 'ff-aid' property
func (c *Client) FfAid() (prop interface{}, err error) {
	return c.GetProperty("ff-aid")
}

// FfSid gets 'ff-sid' property
func (c *Client) FfSid() (prop interface{}, err error) {
	return c.GetProperty("ff-sid")
}

// WindowMinimized gets 'window-minimized' property
func (c *Client) WindowMinimized() (prop interface{}, err error) {
	return c.GetProperty("window-minimized")
}

// DisplayNames gets 'display-names' property
func (c *Client) DisplayNames() (prop interface{}, err error) {
	return c.GetProperty("display-names")
}

// DisplayFps gets 'display-fps' property
func (c *Client) DisplayFps() (prop interface{}, err error) {
	return c.GetProperty("display-fps")
}

// EstimatedDisplayFps gets 'estimated-display-fps' property
func (c *Client) EstimatedDisplayFps() (prop interface{}, err error) {
	return c.GetProperty("estimated-display-fps")
}

// VsyncJitter gets 'vsync-jitter' property
func (c *Client) VsyncJitter() (prop interface{}, err error) {
	return c.GetProperty("vsync-jitter")
}

// WorkingDirectory gets 'working-directory' property
func (c *Client) WorkingDirectory() (prop interface{}, err error) {
	return c.GetProperty("working-directory")
}

// ProtocolList gets 'protocol-list' property
func (c *Client) ProtocolList() (prop interface{}, err error) {
	return c.GetProperty("protocol-list")
}

// MpvVersion gets 'mpv-version' property
func (c *Client) MpvVersion() (prop interface{}, err error) {
	return c.GetProperty("mpv-version")
}

// MpvConfiguration gets 'mpv-configuration' property
func (c *Client) MpvConfiguration() (prop interface{}, err error) {
	return c.GetProperty("mpv-configuration")
}

// Options gets 'options' property
func (c *Client) Options() (prop interface{}, err error) {
	return c.GetProperty("options")
}

// FileLocalOptions gets 'file-local-options' property
func (c *Client) FileLocalOptions() (prop interface{}, err error) {
	return c.GetProperty("file-local-options")
}

// OptionInfo gets 'option-info' property
func (c *Client) OptionInfo() (prop interface{}, err error) {
	return c.GetProperty("option-info")
}

// PropertyList gets 'property-list' property
func (c *Client) PropertyList() (prop interface{}, err error) {
	return c.GetProperty("property-list")
}

// Video gets 'video' property
func (c *Client) Video() (prop interface{}, err error) {
	return c.GetProperty("video")
}

// Audio gets 'audio' property
func (c *Client) Audio() (prop interface{}, err error) {
	return c.GetProperty("audio")
}

// Sub gets 'sub' property
func (c *Client) Sub() (prop interface{}, err error) {
	return c.GetProperty("sub")
}

// Colormatrix gets 'colormatrix' property
func (c *Client) Colormatrix() (prop interface{}, err error) {
	return c.GetProperty("colormatrix")
}

// ColormatrixInputRange gets 'colormatrix-input-range' property
func (c *Client) ColormatrixInputRange() (prop interface{}, err error) {
	return c.GetProperty("colormatrix-input-range")
}

// ColormatrixPrimaries gets 'colormatrix-primaries' property
func (c *Client) ColormatrixPrimaries() (prop interface{}, err error) {
	return c.GetProperty("colormatrix-primaries")
}

// ColormatrixGamma gets 'colormatrix-gamma' property
func (c *Client) ColormatrixGamma() (prop interface{}, err error) {
	return c.GetProperty("colormatrix-gamma")
}

// AudioFormat gets 'audio-format' property
func (c *Client) AudioFormat() (prop interface{}, err error) {
	return c.GetProperty("audio-format")
}

// property setters
func (c *Client) SetProperty(name string, value interface{}) (err error) {
	ch, err := c.Execute("set_property", name, value)
	reply, err := ReplyOrTimeout(ch, WaitForReply)
	if err != nil {
		err = fmt.Errorf("mpv.SetProperty: '%s': %s", name, err)
		return
	}
	if reply.Error != "success" {
		err = fmt.Errorf("mpv.SetProperty: '%s': %s", name, reply.Error)
		return
	}

	return
}

// SetOsdLevel sets 'osd-level' property
func (c *Client) SetOsdLevel(value interface{}) error {
	return c.SetProperty("osd-level", value)
}

// SetOsdScale sets 'osd-scale' property
func (c *Client) SetOsdScale(value interface{}) error {
	return c.SetProperty("osd-scale", value)
}

// SetLoop sets 'loop' property
func (c *Client) SetLoop(value interface{}) error {
	return c.SetProperty("loop", value)
}

// SetLoopFile sets 'loop-file' property
func (c *Client) SetLoopFile(value interface{}) error {
	return c.SetProperty("loop-file", value)
}

// SetSpeed sets 'speed' property
func (c *Client) SetSpeed(value interface{}) error {
	return c.SetProperty("speed", value)
}

// SetAudioSpeedCorrection sets 'audio-speed-correction' property
func (c *Client) SetAudioSpeedCorrection(value interface{}) error {
	return c.SetProperty("audio-speed-correction", value)
}

// SetVideoSpeedCorrection sets 'video-speed-correction' property
func (c *Client) SetVideoSpeedCorrection(value interface{}) error {
	return c.SetProperty("video-speed-correction", value)
}

// SetDisplaySyncActive sets 'display-sync-active' property
func (c *Client) SetDisplaySyncActive(value interface{}) error {
	return c.SetProperty("display-sync-active", value)
}

// SetFilename sets 'filename' property
func (c *Client) SetFilename(value interface{}) error {
	return c.SetProperty("filename", value)
}

// SetStreamOpenFilename sets 'stream-open-filename' property
func (c *Client) SetStreamOpenFilename(value interface{}) error {
	return c.SetProperty("stream-open-filename", value)
}

// SetFileSize sets 'file-size' property
func (c *Client) SetFileSize(value interface{}) error {
	return c.SetProperty("file-size", value)
}

// SetPath sets 'path' property
func (c *Client) SetPath(value interface{}) error {
	return c.SetProperty("path", value)
}

// SetMediaTitle sets 'media-title' property
func (c *Client) SetMediaTitle(value interface{}) error {
	return c.SetProperty("media-title", value)
}

// SetStreamPath sets 'stream-path' property
func (c *Client) SetStreamPath(value interface{}) error {
	return c.SetProperty("stream-path", value)
}

// SetStreamCapture sets 'stream-capture' property
func (c *Client) SetStreamCapture(value interface{}) error {
	return c.SetProperty("stream-capture", value)
}

// SetDemuxer sets 'demuxer' property
func (c *Client) SetDemuxer(value interface{}) error {
	return c.SetProperty("demuxer", value)
}

// SetFileFormat sets 'file-format' property
func (c *Client) SetFileFormat(value interface{}) error {
	return c.SetProperty("file-format", value)
}

// SetStreamPos sets 'stream-pos' property
func (c *Client) SetStreamPos(value interface{}) error {
	return c.SetProperty("stream-pos", value)
}

// SetStreamEnd sets 'stream-end' property
func (c *Client) SetStreamEnd(value interface{}) error {
	return c.SetProperty("stream-end", value)
}

// SetDuration sets 'duration' property
func (c *Client) SetDuration(value interface{}) error {
	return c.SetProperty("duration", value)
}

// SetLength sets 'length' property
func (c *Client) SetLength(value interface{}) error {
	return c.SetProperty("length", value)
}

// SetAvsync sets 'avsync' property
func (c *Client) SetAvsync(value interface{}) error {
	return c.SetProperty("avsync", value)
}

// SetTotalAvsyncChange sets 'total-avsync-change' property
func (c *Client) SetTotalAvsyncChange(value interface{}) error {
	return c.SetProperty("total-avsync-change", value)
}

// SetDropFrameCount sets 'drop-frame-count' property
func (c *Client) SetDropFrameCount(value interface{}) error {
	return c.SetProperty("drop-frame-count", value)
}

// SetMistimedFrameCount sets 'mistimed-frame-count' property
func (c *Client) SetMistimedFrameCount(value interface{}) error {
	return c.SetProperty("mistimed-frame-count", value)
}

// SetVsyncRatio sets 'vsync-ratio' property
func (c *Client) SetVsyncRatio(value interface{}) error {
	return c.SetProperty("vsync-ratio", value)
}

// SetVoDropFrameCount sets 'vo-drop-frame-count' property
func (c *Client) SetVoDropFrameCount(value interface{}) error {
	return c.SetProperty("vo-drop-frame-count", value)
}

// SetVoDelayedFrameCount sets 'vo-delayed-frame-count' property
func (c *Client) SetVoDelayedFrameCount(value interface{}) error {
	return c.SetProperty("vo-delayed-frame-count", value)
}

// SetPercentPos sets 'percent-pos' property
func (c *Client) SetPercentPos(value interface{}) error {
	return c.SetProperty("percent-pos", value)
}

// SetTimeStart sets 'time-start' property
func (c *Client) SetTimeStart(value interface{}) error {
	return c.SetProperty("time-start", value)
}

// SetTimePos sets 'time-pos' property
func (c *Client) SetTimePos(value interface{}) error {
	return c.SetProperty("time-pos", value)
}

// SetTimeRemaining sets 'time-remaining' property
func (c *Client) SetTimeRemaining(value interface{}) error {
	return c.SetProperty("time-remaining", value)
}

// SetPlaytimeRemaining sets 'playtime-remaining' property
func (c *Client) SetPlaytimeRemaining(value interface{}) error {
	return c.SetProperty("playtime-remaining", value)
}

// SetPlaybackTime sets 'playback-time' property
func (c *Client) SetPlaybackTime(value interface{}) error {
	return c.SetProperty("playback-time", value)
}

// SetDiscTitle sets 'disc-title' property
func (c *Client) SetDiscTitle(value interface{}) error {
	return c.SetProperty("disc-title", value)
}

// SetChapter sets 'chapter' property
func (c *Client) SetChapter(value interface{}) error {
	return c.SetProperty("chapter", value)
}

// SetEdition sets 'edition' property
func (c *Client) SetEdition(value interface{}) error {
	return c.SetProperty("edition", value)
}

// SetDiscTitles sets 'disc-titles' property
func (c *Client) SetDiscTitles(value interface{}) error {
	return c.SetProperty("disc-titles", value)
}

// SetChapters sets 'chapters' property
func (c *Client) SetChapters(value interface{}) error {
	return c.SetProperty("chapters", value)
}

// SetEditions sets 'editions' property
func (c *Client) SetEditions(value interface{}) error {
	return c.SetProperty("editions", value)
}

// SetAngle sets 'angle' property
func (c *Client) SetAngle(value interface{}) error {
	return c.SetProperty("angle", value)
}

// SetMetadata sets 'metadata' property
func (c *Client) SetMetadata(value interface{}) error {
	return c.SetProperty("metadata", value)
}

// SetFilteredMetadata sets 'filtered-metadata' property
func (c *Client) SetFilteredMetadata(value interface{}) error {
	return c.SetProperty("filtered-metadata", value)
}

// SetChapterMetadata sets 'chapter-metadata' property
func (c *Client) SetChapterMetadata(value interface{}) error {
	return c.SetProperty("chapter-metadata", value)
}

// SetVfMetadata sets 'vf-metadata' property
func (c *Client) SetVfMetadata(value interface{}) error {
	return c.SetProperty("vf-metadata", value)
}

// SetAfMetadata sets 'af-metadata' property
func (c *Client) SetAfMetadata(value interface{}) error {
	return c.SetProperty("af-metadata", value)
}

// SetPause sets 'pause' property
func (c *Client) SetPause(value interface{}) error {
	return c.SetProperty("pause", value)
}

// SetCoreIdle sets 'core-idle' property
func (c *Client) SetCoreIdle(value interface{}) error {
	return c.SetProperty("core-idle", value)
}

// SetEofReached sets 'eof-reached' property
func (c *Client) SetEofReached(value interface{}) error {
	return c.SetProperty("eof-reached", value)
}

// SetSeeking sets 'seeking' property
func (c *Client) SetSeeking(value interface{}) error {
	return c.SetProperty("seeking", value)
}

// SetPlaybackAbort sets 'playback-abort' property
func (c *Client) SetPlaybackAbort(value interface{}) error {
	return c.SetProperty("playback-abort", value)
}

// SetCache sets 'cache' property
func (c *Client) SetCache(value interface{}) error {
	return c.SetProperty("cache", value)
}

// SetCacheFree sets 'cache-free' property
func (c *Client) SetCacheFree(value interface{}) error {
	return c.SetProperty("cache-free", value)
}

// SetCacheUsed sets 'cache-used' property
func (c *Client) SetCacheUsed(value interface{}) error {
	return c.SetProperty("cache-used", value)
}

// SetCacheSize sets 'cache-size' property
func (c *Client) SetCacheSize(value interface{}) error {
	return c.SetProperty("cache-size", value)
}

// SetCacheIdle sets 'cache-idle' property
func (c *Client) SetCacheIdle(value interface{}) error {
	return c.SetProperty("cache-idle", value)
}

// SetDemuxerCacheDuration sets 'demuxer-cache-duration' property
func (c *Client) SetDemuxerCacheDuration(value interface{}) error {
	return c.SetProperty("demuxer-cache-duration", value)
}

// SetDemuxerCacheTime sets 'demuxer-cache-time' property
func (c *Client) SetDemuxerCacheTime(value interface{}) error {
	return c.SetProperty("demuxer-cache-time", value)
}

// SetDemuxerCacheIdle sets 'demuxer-cache-idle' property
func (c *Client) SetDemuxerCacheIdle(value interface{}) error {
	return c.SetProperty("demuxer-cache-idle", value)
}

// SetCacheBufferingState sets 'cache-buffering-state' property
func (c *Client) SetCacheBufferingState(value interface{}) error {
	return c.SetProperty("cache-buffering-state", value)
}

// SetPausedForCache sets 'paused-for-cache' property
func (c *Client) SetPausedForCache(value interface{}) error {
	return c.SetProperty("paused-for-cache", value)
}

// SetHrSeek sets 'hr-seek' property
func (c *Client) SetHrSeek(value interface{}) error {
	return c.SetProperty("hr-seek", value)
}

// SetClock sets 'clock' property
func (c *Client) SetClock(value interface{}) error {
	return c.SetProperty("clock", value)
}

// SetSeekable sets 'seekable' property
func (c *Client) SetSeekable(value interface{}) error {
	return c.SetProperty("seekable", value)
}

// SetPartiallySeekable sets 'partially-seekable' property
func (c *Client) SetPartiallySeekable(value interface{}) error {
	return c.SetProperty("partially-seekable", value)
}

// SetIdle sets 'idle' property
func (c *Client) SetIdle(value interface{}) error {
	return c.SetProperty("idle", value)
}

// SetChapterList sets 'chapter-list' property
func (c *Client) SetChapterList(value interface{}) error {
	return c.SetProperty("chapter-list", value)
}

// SetTrackList sets 'track-list' property
func (c *Client) SetTrackList(value interface{}) error {
	return c.SetProperty("track-list", value)
}

// SetEditionList sets 'edition-list' property
func (c *Client) SetEditionList(value interface{}) error {
	return c.SetProperty("edition-list", value)
}

// SetDiscTitleList sets 'disc-title-list' property
func (c *Client) SetDiscTitleList(value interface{}) error {
	return c.SetProperty("disc-title-list", value)
}

// SetPlaylist sets 'playlist' property
func (c *Client) SetPlaylist(value interface{}) error {
	return c.SetProperty("playlist", value)
}

// SetPlaylistPos sets 'playlist-pos' property
func (c *Client) SetPlaylistPos(value interface{}) error {
	return c.SetProperty("playlist-pos", value)
}

// SetPlaylistCount sets 'playlist-count' property
func (c *Client) SetPlaylistCount(value interface{}) error {
	return c.SetProperty("playlist-count", value)
}

// SetVolume sets 'volume' property
func (c *Client) SetVolume(value interface{}) error {
	return c.SetProperty("volume", value)
}

// SetMute sets 'mute' property
func (c *Client) SetMute(value interface{}) error {
	return c.SetProperty("mute", value)
}

// SetAudioDelay sets 'audio-delay' property
func (c *Client) SetAudioDelay(value interface{}) error {
	return c.SetProperty("audio-delay", value)
}

// SetAudioCodecName sets 'audio-codec-name' property
func (c *Client) SetAudioCodecName(value interface{}) error {
	return c.SetProperty("audio-codec-name", value)
}

// SetAudioCodec sets 'audio-codec' property
func (c *Client) SetAudioCodec(value interface{}) error {
	return c.SetProperty("audio-codec", value)
}

// SetAudioParams sets 'audio-params' property
func (c *Client) SetAudioParams(value interface{}) error {
	return c.SetProperty("audio-params", value)
}

// SetAudioOutParams sets 'audio-out-params' property
func (c *Client) SetAudioOutParams(value interface{}) error {
	return c.SetProperty("audio-out-params", value)
}

// SetAudioSamplerate sets 'audio-samplerate' property
func (c *Client) SetAudioSamplerate(value interface{}) error {
	return c.SetProperty("audio-samplerate", value)
}

// SetAudioChannels sets 'audio-channels' property
func (c *Client) SetAudioChannels(value interface{}) error {
	return c.SetProperty("audio-channels", value)
}

// SetAid sets 'aid' property
func (c *Client) SetAid(value interface{}) error {
	return c.SetProperty("aid", value)
}

// SetBalance sets 'balance' property
func (c *Client) SetBalance(value interface{}) error {
	return c.SetProperty("balance", value)
}

// SetVolumeRestoreData sets 'volume-restore-data' property
func (c *Client) SetVolumeRestoreData(value interface{}) error {
	return c.SetProperty("volume-restore-data", value)
}

// SetAudioDevice sets 'audio-device' property
func (c *Client) SetAudioDevice(value interface{}) error {
	return c.SetProperty("audio-device", value)
}

// SetAudioDeviceList sets 'audio-device-list' property
func (c *Client) SetAudioDeviceList(value interface{}) error {
	return c.SetProperty("audio-device-list", value)
}

// SetCurrentAo sets 'current-ao' property
func (c *Client) SetCurrentAo(value interface{}) error {
	return c.SetProperty("current-ao", value)
}

// SetAudioOutDetectedDevice sets 'audio-out-detected-device' property
func (c *Client) SetAudioOutDetectedDevice(value interface{}) error {
	return c.SetProperty("audio-out-detected-device", value)
}

// SetFullscreen sets 'fullscreen' property
func (c *Client) SetFullscreen(value interface{}) error {
	return c.SetProperty("fullscreen", value)
}

// SetDeinterlace sets 'deinterlace' property
func (c *Client) SetDeinterlace(value interface{}) error {
	return c.SetProperty("deinterlace", value)
}

// SetFieldDominance sets 'field-dominance' property
func (c *Client) SetFieldDominance(value interface{}) error {
	return c.SetProperty("field-dominance", value)
}

// SetOntop sets 'ontop' property
func (c *Client) SetOntop(value interface{}) error {
	return c.SetProperty("ontop", value)
}

// SetBorder sets 'border' property
func (c *Client) SetBorder(value interface{}) error {
	return c.SetProperty("border", value)
}

// SetOnAllWorkspaces sets 'on-all-workspaces' property
func (c *Client) SetOnAllWorkspaces(value interface{}) error {
	return c.SetProperty("on-all-workspaces", value)
}

// SetFramedrop sets 'framedrop' property
func (c *Client) SetFramedrop(value interface{}) error {
	return c.SetProperty("framedrop", value)
}

// SetGamma sets 'gamma' property
func (c *Client) SetGamma(value interface{}) error {
	return c.SetProperty("gamma", value)
}

// SetBrightness sets 'brightness' property
func (c *Client) SetBrightness(value interface{}) error {
	return c.SetProperty("brightness", value)
}

// SetContrast sets 'contrast' property
func (c *Client) SetContrast(value interface{}) error {
	return c.SetProperty("contrast", value)
}

// SetSaturation sets 'saturation' property
func (c *Client) SetSaturation(value interface{}) error {
	return c.SetProperty("saturation", value)
}

// SetHue sets 'hue' property
func (c *Client) SetHue(value interface{}) error {
	return c.SetProperty("hue", value)
}

// SetVideoOutputLevels sets 'video-output-levels' property
func (c *Client) SetVideoOutputLevels(value interface{}) error {
	return c.SetProperty("video-output-levels", value)
}

// SetPanscan sets 'panscan' property
func (c *Client) SetPanscan(value interface{}) error {
	return c.SetProperty("panscan", value)
}

// SetVideoZoom sets 'video-zoom' property
func (c *Client) SetVideoZoom(value interface{}) error {
	return c.SetProperty("video-zoom", value)
}

// SetVideoAlignX sets 'video-align-x' property
func (c *Client) SetVideoAlignX(value interface{}) error {
	return c.SetProperty("video-align-x", value)
}

// SetVideoAlignY sets 'video-align-y' property
func (c *Client) SetVideoAlignY(value interface{}) error {
	return c.SetProperty("video-align-y", value)
}

// SetVideoPanX sets 'video-pan-x' property
func (c *Client) SetVideoPanX(value interface{}) error {
	return c.SetProperty("video-pan-x", value)
}

// SetVideoPanY sets 'video-pan-y' property
func (c *Client) SetVideoPanY(value interface{}) error {
	return c.SetProperty("video-pan-y", value)
}

// SetVideoUnscaled sets 'video-unscaled' property
func (c *Client) SetVideoUnscaled(value interface{}) error {
	return c.SetProperty("video-unscaled", value)
}

// SetVideoOutParams sets 'video-out-params' property
func (c *Client) SetVideoOutParams(value interface{}) error {
	return c.SetProperty("video-out-params", value)
}

// SetVideoParams sets 'video-params' property
func (c *Client) SetVideoParams(value interface{}) error {
	return c.SetProperty("video-params", value)
}

// SetVideoFormat sets 'video-format' property
func (c *Client) SetVideoFormat(value interface{}) error {
	return c.SetProperty("video-format", value)
}

// SetVideoFrameInfo sets 'video-frame-info' property
func (c *Client) SetVideoFrameInfo(value interface{}) error {
	return c.SetProperty("video-frame-info", value)
}

// SetVideoCodec sets 'video-codec' property
func (c *Client) SetVideoCodec(value interface{}) error {
	return c.SetProperty("video-codec", value)
}

// SetDwidth sets 'dwidth' property
func (c *Client) SetDwidth(value interface{}) error {
	return c.SetProperty("dwidth", value)
}

// SetDheight sets 'dheight' property
func (c *Client) SetDheight(value interface{}) error {
	return c.SetProperty("dheight", value)
}

// SetWidth sets 'width' property
func (c *Client) SetWidth(value interface{}) error {
	return c.SetProperty("width", value)
}

// SetHeight sets 'height' property
func (c *Client) SetHeight(value interface{}) error {
	return c.SetProperty("height", value)
}

// SetWindowScale sets 'window-scale' property
func (c *Client) SetWindowScale(value interface{}) error {
	return c.SetProperty("window-scale", value)
}

// SetVoConfigured sets 'vo-configured' property
func (c *Client) SetVoConfigured(value interface{}) error {
	return c.SetProperty("vo-configured", value)
}

// SetCurrentVo sets 'current-vo' property
func (c *Client) SetCurrentVo(value interface{}) error {
	return c.SetProperty("current-vo", value)
}

// SetFps sets 'fps' property
func (c *Client) SetFps(value interface{}) error {
	return c.SetProperty("fps", value)
}

// SetEstimatedVfFps sets 'estimated-vf-fps' property
func (c *Client) SetEstimatedVfFps(value interface{}) error {
	return c.SetProperty("estimated-vf-fps", value)
}

// SetVideoAspect sets 'video-aspect' property
func (c *Client) SetVideoAspect(value interface{}) error {
	return c.SetProperty("video-aspect", value)
}

// SetVid sets 'vid' property
func (c *Client) SetVid(value interface{}) error {
	return c.SetProperty("vid", value)
}

// SetProgram sets 'program' property
func (c *Client) SetProgram(value interface{}) error {
	return c.SetProperty("program", value)
}

// SetHwdec sets 'hwdec' property
func (c *Client) SetHwdec(value interface{}) error {
	return c.SetProperty("hwdec", value)
}

// SetHwdecActive sets 'hwdec-active' property
func (c *Client) SetHwdecActive(value interface{}) error {
	return c.SetProperty("hwdec-active", value)
}

// SetHwdecDetected sets 'hwdec-detected' property
func (c *Client) SetHwdecDetected(value interface{}) error {
	return c.SetProperty("hwdec-detected", value)
}

// SetEstimatedFrameCount sets 'estimated-frame-count' property
func (c *Client) SetEstimatedFrameCount(value interface{}) error {
	return c.SetProperty("estimated-frame-count", value)
}

// SetEstimatedFrameNumber sets 'estimated-frame-number' property
func (c *Client) SetEstimatedFrameNumber(value interface{}) error {
	return c.SetProperty("estimated-frame-number", value)
}

// SetOsdWidth sets 'osd-width' property
func (c *Client) SetOsdWidth(value interface{}) error {
	return c.SetProperty("osd-width", value)
}

// SetOsdHeight sets 'osd-height' property
func (c *Client) SetOsdHeight(value interface{}) error {
	return c.SetProperty("osd-height", value)
}

// SetOsdPar sets 'osd-par' property
func (c *Client) SetOsdPar(value interface{}) error {
	return c.SetProperty("osd-par", value)
}

// SetOsdSymCc sets 'osd-sym-cc' property
func (c *Client) SetOsdSymCc(value interface{}) error {
	return c.SetProperty("osd-sym-cc", value)
}

// SetOsdAssCc sets 'osd-ass-cc' property
func (c *Client) SetOsdAssCc(value interface{}) error {
	return c.SetProperty("osd-ass-cc", value)
}

// SetSid sets 'sid' property
func (c *Client) SetSid(value interface{}) error {
	return c.SetProperty("sid", value)
}

// SetSecondarySid sets 'secondary-sid' property
func (c *Client) SetSecondarySid(value interface{}) error {
	return c.SetProperty("secondary-sid", value)
}

// SetSubDelay sets 'sub-delay' property
func (c *Client) SetSubDelay(value interface{}) error {
	return c.SetProperty("sub-delay", value)
}

// SetSubPos sets 'sub-pos' property
func (c *Client) SetSubPos(value interface{}) error {
	return c.SetProperty("sub-pos", value)
}

// SetSubVisibility sets 'sub-visibility' property
func (c *Client) SetSubVisibility(value interface{}) error {
	return c.SetProperty("sub-visibility", value)
}

// SetSubForcedOnly sets 'sub-forced-only' property
func (c *Client) SetSubForcedOnly(value interface{}) error {
	return c.SetProperty("sub-forced-only", value)
}

// SetSubScale sets 'sub-scale' property
func (c *Client) SetSubScale(value interface{}) error {
	return c.SetProperty("sub-scale", value)
}

// SetSubUseMargins sets 'sub-use-margins' property
func (c *Client) SetSubUseMargins(value interface{}) error {
	return c.SetProperty("sub-use-margins", value)
}

// SetAssForceMargins sets 'ass-force-margins' property
func (c *Client) SetAssForceMargins(value interface{}) error {
	return c.SetProperty("ass-force-margins", value)
}

// SetAssVsfilterAspectCompat sets 'ass-vsfilter-aspect-compat' property
func (c *Client) SetAssVsfilterAspectCompat(value interface{}) error {
	return c.SetProperty("ass-vsfilter-aspect-compat", value)
}

// SetAssStyleOverride sets 'ass-style-override' property
func (c *Client) SetAssStyleOverride(value interface{}) error {
	return c.SetProperty("ass-style-override", value)
}

// SetVideoRotate sets 'video-rotate' property
func (c *Client) SetVideoRotate(value interface{}) error {
	return c.SetProperty("video-rotate", value)
}

// SetAbLoopA sets 'ab-loop-a' property
func (c *Client) SetAbLoopA(value interface{}) error {
	return c.SetProperty("ab-loop-a", value)
}

// SetAbLoopB sets 'ab-loop-b' property
func (c *Client) SetAbLoopB(value interface{}) error {
	return c.SetProperty("ab-loop-b", value)
}

// SetPacketVideoBitrate sets 'packet-video-bitrate' property
func (c *Client) SetPacketVideoBitrate(value interface{}) error {
	return c.SetProperty("packet-video-bitrate", value)
}

// SetPacketAudioBitrate sets 'packet-audio-bitrate' property
func (c *Client) SetPacketAudioBitrate(value interface{}) error {
	return c.SetProperty("packet-audio-bitrate", value)
}

// SetPacketSubBitrate sets 'packet-sub-bitrate' property
func (c *Client) SetPacketSubBitrate(value interface{}) error {
	return c.SetProperty("packet-sub-bitrate", value)
}

// SetVideoBitrate sets 'video-bitrate' property
func (c *Client) SetVideoBitrate(value interface{}) error {
	return c.SetProperty("video-bitrate", value)
}

// SetAudioBitrate sets 'audio-bitrate' property
func (c *Client) SetAudioBitrate(value interface{}) error {
	return c.SetProperty("audio-bitrate", value)
}

// SetSubBitrate sets 'sub-bitrate' property
func (c *Client) SetSubBitrate(value interface{}) error {
	return c.SetProperty("sub-bitrate", value)
}

// SetTvBrightness sets 'tv-brightness' property
func (c *Client) SetTvBrightness(value interface{}) error {
	return c.SetProperty("tv-brightness", value)
}

// SetTvContrast sets 'tv-contrast' property
func (c *Client) SetTvContrast(value interface{}) error {
	return c.SetProperty("tv-contrast", value)
}

// SetTvSaturation sets 'tv-saturation' property
func (c *Client) SetTvSaturation(value interface{}) error {
	return c.SetProperty("tv-saturation", value)
}

// SetTvHue sets 'tv-hue' property
func (c *Client) SetTvHue(value interface{}) error {
	return c.SetProperty("tv-hue", value)
}

// SetTvFreq sets 'tv-freq' property
func (c *Client) SetTvFreq(value interface{}) error {
	return c.SetProperty("tv-freq", value)
}

// SetTvNorm sets 'tv-norm' property
func (c *Client) SetTvNorm(value interface{}) error {
	return c.SetProperty("tv-norm", value)
}

// SetTvScan sets 'tv-scan' property
func (c *Client) SetTvScan(value interface{}) error {
	return c.SetProperty("tv-scan", value)
}

// SetTvChannel sets 'tv-channel' property
func (c *Client) SetTvChannel(value interface{}) error {
	return c.SetProperty("tv-channel", value)
}

// SetDvbChannel sets 'dvb-channel' property
func (c *Client) SetDvbChannel(value interface{}) error {
	return c.SetProperty("dvb-channel", value)
}

// SetCursorAutohide sets 'cursor-autohide' property
func (c *Client) SetCursorAutohide(value interface{}) error {
	return c.SetProperty("cursor-autohide", value)
}

// SetFfVid sets 'ff-vid' property
func (c *Client) SetFfVid(value interface{}) error {
	return c.SetProperty("ff-vid", value)
}

// SetFfAid sets 'ff-aid' property
func (c *Client) SetFfAid(value interface{}) error {
	return c.SetProperty("ff-aid", value)
}

// SetFfSid sets 'ff-sid' property
func (c *Client) SetFfSid(value interface{}) error {
	return c.SetProperty("ff-sid", value)
}

// SetWindowMinimized sets 'window-minimized' property
func (c *Client) SetWindowMinimized(value interface{}) error {
	return c.SetProperty("window-minimized", value)
}

// SetDisplayNames sets 'display-names' property
func (c *Client) SetDisplayNames(value interface{}) error {
	return c.SetProperty("display-names", value)
}

// SetDisplayFps sets 'display-fps' property
func (c *Client) SetDisplayFps(value interface{}) error {
	return c.SetProperty("display-fps", value)
}

// SetEstimatedDisplayFps sets 'estimated-display-fps' property
func (c *Client) SetEstimatedDisplayFps(value interface{}) error {
	return c.SetProperty("estimated-display-fps", value)
}

// SetVsyncJitter sets 'vsync-jitter' property
func (c *Client) SetVsyncJitter(value interface{}) error {
	return c.SetProperty("vsync-jitter", value)
}

// SetWorkingDirectory sets 'working-directory' property
func (c *Client) SetWorkingDirectory(value interface{}) error {
	return c.SetProperty("working-directory", value)
}

// SetProtocolList sets 'protocol-list' property
func (c *Client) SetProtocolList(value interface{}) error {
	return c.SetProperty("protocol-list", value)
}

// SetMpvVersion sets 'mpv-version' property
func (c *Client) SetMpvVersion(value interface{}) error {
	return c.SetProperty("mpv-version", value)
}

// SetMpvConfiguration sets 'mpv-configuration' property
func (c *Client) SetMpvConfiguration(value interface{}) error {
	return c.SetProperty("mpv-configuration", value)
}

// SetOptions sets 'options' property
func (c *Client) SetOptions(value interface{}) error {
	return c.SetProperty("options", value)
}

// SetFileLocalOptions sets 'file-local-options' property
func (c *Client) SetFileLocalOptions(value interface{}) error {
	return c.SetProperty("file-local-options", value)
}

// SetOptionInfo sets 'option-info' property
func (c *Client) SetOptionInfo(value interface{}) error {
	return c.SetProperty("option-info", value)
}

// SetPropertyList sets 'property-list' property
func (c *Client) SetPropertyList(value interface{}) error {
	return c.SetProperty("property-list", value)
}

// SetVideo sets 'video' property
func (c *Client) SetVideo(value interface{}) error {
	return c.SetProperty("video", value)
}

// SetAudio sets 'audio' property
func (c *Client) SetAudio(value interface{}) error {
	return c.SetProperty("audio", value)
}

// SetSub sets 'sub' property
func (c *Client) SetSub(value interface{}) error {
	return c.SetProperty("sub", value)
}

// SetColormatrix sets 'colormatrix' property
func (c *Client) SetColormatrix(value interface{}) error {
	return c.SetProperty("colormatrix", value)
}

// SetColormatrixInputRange sets 'colormatrix-input-range' property
func (c *Client) SetColormatrixInputRange(value interface{}) error {
	return c.SetProperty("colormatrix-input-range", value)
}

// SetColormatrixPrimaries sets 'colormatrix-primaries' property
func (c *Client) SetColormatrixPrimaries(value interface{}) error {
	return c.SetProperty("colormatrix-primaries", value)
}

// SetColormatrixGamma sets 'colormatrix-gamma' property
func (c *Client) SetColormatrixGamma(value interface{}) error {
	return c.SetProperty("colormatrix-gamma", value)
}

// SetAudioFormat sets 'audio-format' property
func (c *Client) SetAudioFormat(value interface{}) error {
	return c.SetProperty("audio-format", value)
}

